server.port=8081

spring.datasource.url=jdbc:postgresql://dpg-d1fh13qdbo4c73fj2m7g-a.oregon-postgres.render.com:5432/portafolio_db_fae4
spring.datasource.username=portafolio_db_fae4_user
spring.datasource.password=3qYtJEbMlk1A1p1rQqbOmTPVbQor0mw9

#spring.datasource.url=jdbc:postgresql://localhost:5432/ferreSas
#spring.datasource.username=postgres
#spring.datasource.password=Maxter666!
spring.datasource.driver-class-name=org.postgresql.Driver


spring.jpa.hibernate.ddl-auto=create
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

transbank.webpay.commerce-code=597055555532
transbank.webpay.api-key=579B532A7440BB0C9079DED94D31EA1615BACEB56610332264630D42D0A36B1C
transbank.webpay.environment=TEST