server.port=8080

spring.datasource.url=jdbc:postgresql://dpg-d0qaejbipnbc73e6ujmg-a.oregon-postgres.render.com:5432/portafolio_db_l4a7
spring.datasource.username=portafolio_db_l4a7_user
spring.datasource.password=jqBoLGxs4t6NVsiGxsP3VbMJManZr6ml

spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=create
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect